
package org.api.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SistemaWS", targetNamespace = "http://ws.api.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SistemaWS {


    /**
     * 
     * @return
     *     returns java.util.List<org.api.ws.client.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarClientes", targetNamespace = "http://ws.api.org/", className = "org.api.ws.client.ListarClientes")
    @ResponseWrapper(localName = "listarClientesResponse", targetNamespace = "http://ws.api.org/", className = "org.api.ws.client.ListarClientesResponse")
    @Action(input = "http://ws.api.org/SistemaWS/listarClientesRequest", output = "http://ws.api.org/SistemaWS/listarClientesResponse")
    public List<Cliente> listarClientes();

    /**
     * 
     * @return
     *     returns java.util.List<org.api.ws.client.Produto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarProdutos", targetNamespace = "http://ws.api.org/", className = "org.api.ws.client.ListarProdutos")
    @ResponseWrapper(localName = "listarProdutosResponse", targetNamespace = "http://ws.api.org/", className = "org.api.ws.client.ListarProdutosResponse")
    @Action(input = "http://ws.api.org/SistemaWS/listarProdutosRequest", output = "http://ws.api.org/SistemaWS/listarProdutosResponse")
    public List<Produto> listarProdutos();

    /**
     * 
     * @param cliente
     * @return
     *     returns org.api.ws.client.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarCliente", targetNamespace = "http://ws.api.org/", className = "org.api.ws.client.CadastrarCliente")
    @ResponseWrapper(localName = "cadastrarClienteResponse", targetNamespace = "http://ws.api.org/", className = "org.api.ws.client.CadastrarClienteResponse")
    @Action(input = "http://ws.api.org/SistemaWS/cadastrarClienteRequest", output = "http://ws.api.org/SistemaWS/cadastrarClienteResponse")
    public Cliente cadastrarCliente(
        @WebParam(name = "cliente", targetNamespace = "")
        Cliente cliente);

    /**
     * 
     * @param produto
     * @return
     *     returns org.api.ws.client.Produto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarProduto", targetNamespace = "http://ws.api.org/", className = "org.api.ws.client.CadastrarProduto")
    @ResponseWrapper(localName = "cadastrarProdutoResponse", targetNamespace = "http://ws.api.org/", className = "org.api.ws.client.CadastrarProdutoResponse")
    @Action(input = "http://ws.api.org/SistemaWS/cadastrarProdutoRequest", output = "http://ws.api.org/SistemaWS/cadastrarProdutoResponse")
    public Produto cadastrarProduto(
        @WebParam(name = "produto", targetNamespace = "")
        Produto produto);

}
