
package org.api.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SistemaWSImplService", targetNamespace = "http://ws.api.org/", wsdlLocation = "http://localhost:8080/sistema?wsdl")
public class SistemaWSImplService
    extends Service
{

    private final static URL SISTEMAWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SISTEMAWSIMPLSERVICE_EXCEPTION;
    private final static QName SISTEMAWSIMPLSERVICE_QNAME = new QName("http://ws.api.org/", "SistemaWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sistema?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SISTEMAWSIMPLSERVICE_WSDL_LOCATION = url;
        SISTEMAWSIMPLSERVICE_EXCEPTION = e;
    }

    public SistemaWSImplService() {
        super(__getWsdlLocation(), SISTEMAWSIMPLSERVICE_QNAME);
    }

    public SistemaWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISTEMAWSIMPLSERVICE_QNAME, features);
    }

    public SistemaWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SISTEMAWSIMPLSERVICE_QNAME);
    }

    public SistemaWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISTEMAWSIMPLSERVICE_QNAME, features);
    }

    public SistemaWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SistemaWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SistemaWS
     */
    @WebEndpoint(name = "SistemaWSImplPort")
    public SistemaWS getSistemaWSImplPort() {
        return super.getPort(new QName("http://ws.api.org/", "SistemaWSImplPort"), SistemaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SistemaWS
     */
    @WebEndpoint(name = "SistemaWSImplPort")
    public SistemaWS getSistemaWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.api.org/", "SistemaWSImplPort"), SistemaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISTEMAWSIMPLSERVICE_EXCEPTION!= null) {
            throw SISTEMAWSIMPLSERVICE_EXCEPTION;
        }
        return SISTEMAWSIMPLSERVICE_WSDL_LOCATION;
    }

}
